# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for specific files and path
  push:
    # paths:
    # - '**.html'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs html validation from "https://github.com/svenkreiss/html5validator"
      - name: Html5 Validatior
        id: validate
        uses: Cyb3r-Jak3/html5validator-action-experimental@v1
        with:
          root: src/
          format: xml
          log_level: DEBUG
          css: true

      - name: Check outputs
        run: |
          if [[ "$VALID_OUT" -ne 1 ]]; then
            echo "Validation step failed"
            exit 1
          fi
        env:
          VALID_OUT: ${{ steps.validate.outputs.result }}

      # Runs a set of commands using the runners shell
      - uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.log
